#!/usr/bin/env python3
"""
DAY039 / D039-A3

Electrostatic-preservation audit of candidate artificial-cap charge
redistribution strategies for QM_F06_UPPER_V7A_R1.

Reference potential:
    Coulomb potential generated by all 52 RESP Stage 1 charges.

Candidate potentials:
    Coulomb potentials generated by the 37 retained real atoms after
    applying each exploratory redistribution strategy.

No redistribution strategy is adopted.
RESP Stage 2 remains blocked.
"""

from __future__ import annotations

import csv
import json
import math
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from resp_common import (
    load_json,
    read_orca_vpot,
    require_file,
    sha256,
)


ROOT = Path(__file__).resolve().parents[2]

EXECUTION_PARENT = (
    ROOT
    / "runs/phase1A/day038_resp_stage1_executions"
)

LATEST_POINTER = (
    EXECUTION_PARENT
    / "LATEST_RESP_STAGE1_UPPER_V7A_R1_EXECUTION.txt"
)

VPOT = (
    ROOT
    / "runs/phase1A/day036_qm_f06_upper_v7a_r1_esp_executions"
    / "esp_upper_v7a_r1_20260731T174832Z"
    / "esp_upper_v7a_r1.vpot"
)

EXPECTED_COMPARISON_DECISION = (
    "D039_A2_CAP_REDISTRIBUTION_STRATEGY_COMPARISON_PASS_"
    "SCIENTIFIC_SELECTION_REVIEW_AUTHORIZED"
)

EXPECTED_VPOT_SHA256 = (
    "73df47796c29d0b2a88a03d83efcb723"
    "d4f6e583d2e1789e1ea1a43d82c1064d"
)

DISTANCE_THRESHOLDS_BOHR = (
    0.0,
    2.5,
    3.0,
    3.5,
    4.0,
    4.5,
    5.0,
)


def parse_bool(value: str) -> bool:
    normalized = value.strip().lower()

    if normalized in {"true", "1", "yes", "y"}:
        return True

    if normalized in {"false", "0", "no", "n", ""}:
        return False

    raise RuntimeError(
        f"Unrecognized Boolean value: {value!r}"
    )


def coulomb_potential(
    point_xyz_bohr: np.ndarray,
    atom_xyz_bohr: np.ndarray,
    charges_e: np.ndarray,
    chunk_size: int = 2000,
) -> np.ndarray:
    """
    Calculate V(r) = sum_i q_i / |r-R_i| in atomic units.
    """

    values = np.empty(
        len(point_xyz_bohr),
        dtype=float,
    )

    for start in range(
        0,
        len(point_xyz_bohr),
        chunk_size,
    ):
        stop = min(
            start + chunk_size,
            len(point_xyz_bohr),
        )

        displacement = (
            point_xyz_bohr[start:stop, None, :]
            - atom_xyz_bohr[None, :, :]
        )

        distances = np.linalg.norm(
            displacement,
            axis=2,
        )

        if np.any(distances <= 0.0):
            raise RuntimeError(
                "ESP point coincides with an atomic center"
            )

        values[start:stop] = np.sum(
            charges_e[None, :] / distances,
            axis=1,
        )

    return values


def nearest_distance(
    point_xyz_bohr: np.ndarray,
    atom_xyz_bohr: np.ndarray,
    chunk_size: int = 2000,
) -> np.ndarray:
    values = np.empty(
        len(point_xyz_bohr),
        dtype=float,
    )

    for start in range(
        0,
        len(point_xyz_bohr),
        chunk_size,
    ):
        stop = min(
            start + chunk_size,
            len(point_xyz_bohr),
        )

        displacement = (
            point_xyz_bohr[start:stop, None, :]
            - atom_xyz_bohr[None, :, :]
        )

        values[start:stop] = np.min(
            np.linalg.norm(
                displacement,
                axis=2,
            ),
            axis=1,
        )

    return values


def vector_metrics(
    reference: np.ndarray,
    candidate: np.ndarray,
) -> dict:
    residual = candidate - reference
    absolute = np.abs(residual)

    reference_centered = (
        reference - np.mean(reference)
    )

    candidate_centered = (
        candidate - np.mean(candidate)
    )

    denominator = math.sqrt(
        float(
            np.sum(reference_centered ** 2)
            * np.sum(candidate_centered ** 2)
        )
    )

    pearson_r = (
        float(
            np.sum(
                reference_centered
                * candidate_centered
            )
            / denominator
        )
        if denominator > 0.0
        else None
    )

    reference_std = float(
        np.std(reference)
    )

    return {
        "point_count": int(len(reference)),
        "reference_mean_au": float(
            np.mean(reference)
        ),
        "reference_std_au": (
            reference_std
        ),
        "candidate_mean_au": float(
            np.mean(candidate)
        ),
        "candidate_std_au": float(
            np.std(candidate)
        ),
        "residual_mean_au": float(
            np.mean(residual)
        ),
        "RMSE_au": float(
            np.sqrt(
                np.mean(residual ** 2)
            )
        ),
        "MAE_au": float(
            np.mean(absolute)
        ),
        "maximum_absolute_error_au": float(
            np.max(absolute)
        ),
        "RMSE_over_reference_std": (
            float(
                np.sqrt(
                    np.mean(residual ** 2)
                )
                / reference_std
            )
            if reference_std > 0.0
            else None
        ),
        "pearson_r": pearson_r,
        "r_squared": (
            pearson_r * pearson_r
            if pearson_r is not None
            else None
        ),
        "same_sign_fraction": float(
            np.mean(
                np.sign(reference)
                == np.sign(candidate)
            )
        ),
        "absolute_error_quantiles_au": {
            "q000": float(
                np.quantile(absolute, 0.00)
            ),
            "q025": float(
                np.quantile(absolute, 0.25)
            ),
            "q050": float(
                np.quantile(absolute, 0.50)
            ),
            "q075": float(
                np.quantile(absolute, 0.75)
            ),
            "q090": float(
                np.quantile(absolute, 0.90)
            ),
            "q095": float(
                np.quantile(absolute, 0.95)
            ),
            "q099": float(
                np.quantile(absolute, 0.99)
            ),
            "q100": float(
                np.quantile(absolute, 1.00)
            ),
        },
    }


print("=" * 100)
print("DAY039 / D039-A3 — ELECTROSTATIC PRESERVATION AUDIT")
print("=" * 100)


print("\n[1] SOURCE FILES")

require_file(LATEST_POINTER)
require_file(VPOT)

execution_dir = (
    ROOT
    / LATEST_POINTER.read_text(
        encoding="utf-8"
    ).strip()
)

transferability_csv = (
    execution_dir
    / "QM_F06_UPPER_V7A_R1_RESP_STAGE1_TRANSFERABILITY.csv"
)

comparison_csv = (
    execution_dir
    / "QM_F06_UPPER_V7A_R1_CAP_REDISTRIBUTION_STRATEGY_COMPARISON.csv"
)

comparison_json = (
    execution_dir
    / "QM_F06_UPPER_V7A_R1_CAP_REDISTRIBUTION_STRATEGY_COMPARISON.json"
)

for path in (
    transferability_csv,
    comparison_csv,
    comparison_json,
):
    require_file(path)
    print(f"FOUND  {path}")

if sha256(VPOT) != EXPECTED_VPOT_SHA256:
    raise RuntimeError(
        "Authorized VPOT SHA256 mismatch"
    )

print(f"VPOT_SHA256 = {sha256(VPOT)}")
print("VPOT_hash_gate = PASS")


print("\n[2] UPSTREAM AUTHORIZATION")

comparison_report = load_json(
    comparison_json
)

if (
    comparison_report.get("decision")
    != EXPECTED_COMPARISON_DECISION
):
    raise RuntimeError(
        "Unexpected redistribution-comparison decision.\n"
        f"Observed: {comparison_report.get('decision')}"
    )

authorizations = comparison_report.get(
    "authorizations",
    {},
)

if (
    authorizations.get(
        "redistribution_strategy_scientific_review_authorized"
    )
    is not True
):
    raise RuntimeError(
        "Electrostatic review is not authorized"
    )

if (
    authorizations.get(
        "redistribution_strategy_adoption_authorized"
    )
    is not False
):
    raise RuntimeError(
        "Unexpected strategy-adoption authorization"
    )

print("upstream_decision_gate       = PASS")
print("scientific_review_gate       = PASS")
print("strategy_adoption_block_gate = PASS")


print("\n[3] LOAD FULL RESP STAGE 1 SYSTEM")

with transferability_csv.open(
    "r",
    encoding="utf-8",
    newline="",
) as handle:
    full_rows = list(
        csv.DictReader(handle)
    )

if len(full_rows) != 52:
    raise RuntimeError(
        f"Expected 52 atoms, observed {len(full_rows)}"
    )

full_rows = sorted(
    full_rows,
    key=lambda row: int(
        row["atom_index_0based"]
    ),
)

full_atom_xyz_bohr = np.asarray(
    [
        (
            float(row["x_A"])
            / 0.529177210903,
            float(row["y_A"])
            / 0.529177210903,
            float(row["z_A"])
            / 0.529177210903,
        )
        for row in full_rows
    ],
    dtype=float,
)

full_charges = np.asarray(
    [
        float(
            row["RESP_stage1_charge_e"]
        )
        for row in full_rows
    ],
    dtype=float,
)

real_rows = [
    row
    for row in full_rows
    if not parse_bool(
        row["artificial_cap"]
    )
]

real_atom_ids = [
    row["atom_id"].strip()
    for row in real_rows
]

real_atom_xyz_bohr = np.asarray(
    [
        (
            float(row["x_A"])
            / 0.529177210903,
            float(row["y_A"])
            / 0.529177210903,
            float(row["z_A"])
            / 0.529177210903,
        )
        for row in real_rows
    ],
    dtype=float,
)

print(f"full_atom_count = {len(full_rows)}")
print(f"real_atom_count = {len(real_rows)}")
print(
    f"full_RESP_charge_sum_e = "
    f"{np.sum(full_charges):.16g}"
)


print("\n[4] LOAD REDISTRIBUTED CHARGE VECTORS")

with comparison_csv.open(
    "r",
    encoding="utf-8",
    newline="",
) as handle:
    redistribution_rows = list(
        csv.DictReader(handle)
    )

if len(redistribution_rows) != 37:
    raise RuntimeError(
        "Expected 37 redistributed real atoms"
    )

redistribution_by_id = {
    row["atom_id"].strip(): row
    for row in redistribution_rows
}

if set(redistribution_by_id) != set(
    real_atom_ids
):
    raise RuntimeError(
        "Redistributed atom set does not match "
        "the retained real-atom set"
    )

strategy_columns = {
    "PARENT_ONLY": (
        "PARENT_ONLY_charge_e"
    ),
    "FIRST_SHELL_EQUAL": (
        "FIRST_SHELL_EQUAL_charge_e"
    ),
    "FIRST_SHELL_ABS_Q_WEIGHTED": (
        "FIRST_SHELL_ABS_Q_WEIGHTED_charge_e"
    ),
}

strategy_charges = {}

for strategy, column in strategy_columns.items():
    values = np.asarray(
        [
            float(
                redistribution_by_id[
                    atom_id
                ][column]
            )
            for atom_id in real_atom_ids
        ],
        dtype=float,
    )

    strategy_charges[strategy] = values

    print(
        f"{strategy}_charge_sum_e = "
        f"{np.sum(values):.16g}"
    )


print("\n[5] LOAD ESP GRID")

vpot = read_orca_vpot(
    VPOT
)

grid_xyz_bohr = np.asarray(
    vpot.grid_coordinates_bohr,
    dtype=float,
)

if grid_xyz_bohr.shape != (
    24835,
    3,
):
    raise RuntimeError(
        "Unexpected VPOT grid shape"
    )

print(
    f"ESP_grid_point_count = "
    f"{len(grid_xyz_bohr)}"
)


print("\n[6] CALCULATE REFERENCE POTENTIAL")

reference_potential = coulomb_potential(
    grid_xyz_bohr,
    full_atom_xyz_bohr,
    full_charges,
)

nearest_real_distance = nearest_distance(
    grid_xyz_bohr,
    real_atom_xyz_bohr,
)

print(
    f"reference_potential_min_au = "
    f"{np.min(reference_potential):.16g}"
)
print(
    f"reference_potential_max_au = "
    f"{np.max(reference_potential):.16g}"
)
print(
    f"reference_potential_mean_au = "
    f"{np.mean(reference_potential):.16g}"
)
print(
    f"reference_potential_std_au = "
    f"{np.std(reference_potential):.16g}"
)


print("\n[7] STRATEGY ELECTROSTATIC METRICS")

strategy_potentials = {}
strategy_metrics = {}

for strategy, charges in (
    strategy_charges.items()
):
    candidate_potential = coulomb_potential(
        grid_xyz_bohr,
        real_atom_xyz_bohr,
        charges,
    )

    strategy_potentials[
        strategy
    ] = candidate_potential

    global_metrics = vector_metrics(
        reference_potential,
        candidate_potential,
    )

    distance_metrics = {}

    for threshold in (
        DISTANCE_THRESHOLDS_BOHR
    ):
        mask = (
            nearest_real_distance >= threshold
        )

        if not np.any(mask):
            continue

        distance_metrics[
            f"rmin_real_ge_{threshold:.1f}_bohr"
        ] = vector_metrics(
            reference_potential[mask],
            candidate_potential[mask],
        )

    strategy_metrics[strategy] = {
        "global": global_metrics,
        "by_minimum_real_atom_distance": (
            distance_metrics
        ),
    }

    print(f"\nStrategy = {strategy}")

    print(
        f"  global_RMSE_au = "
        f"{global_metrics['RMSE_au']:.16g}"
    )
    print(
        f"  global_MAE_au = "
        f"{global_metrics['MAE_au']:.16g}"
    )
    print(
        f"  global_max_abs_error_au = "
        f"{global_metrics['maximum_absolute_error_au']:.16g}"
    )
    print(
        f"  global_RMSE_over_reference_std = "
        f"{global_metrics['RMSE_over_reference_std']:.16g}"
    )
    print(
        f"  global_pearson_r = "
        f"{global_metrics['pearson_r']:.16g}"
    )
    print(
        f"  global_same_sign_fraction = "
        f"{global_metrics['same_sign_fraction']:.16g}"
    )

    for key, metrics in (
        distance_metrics.items()
    ):
        print(
            f"  {key}: "
            f"n={metrics['point_count']} "
            f"RMSE={metrics['RMSE_au']:.8g} "
            f"MAE={metrics['MAE_au']:.8g} "
            f"R={metrics['pearson_r']:.8g}"
        )


print("\n[8] RELATIVE STRATEGY RANKING")

ranking = sorted(
    strategy_metrics,
    key=lambda strategy: (
        strategy_metrics[strategy][
            "global"
        ]["RMSE_au"]
    ),
)

for rank, strategy in enumerate(
    ranking,
    start=1,
):
    metrics = strategy_metrics[
        strategy
    ]["global"]

    print(
        f"rank={rank} "
        f"strategy={strategy} "
        f"RMSE_au={metrics['RMSE_au']:.16g} "
        f"MAE_au={metrics['MAE_au']:.16g} "
        f"max_abs_au="
        f"{metrics['maximum_absolute_error_au']:.16g} "
        f"R={metrics['pearson_r']:.16g}"
    )


print("\n[9] LARGEST POTENTIAL ERRORS")

largest_error_records = {}

for strategy, potential in (
    strategy_potentials.items()
):
    residual = (
        potential - reference_potential
    )

    ranked_indices = np.argsort(
        np.abs(residual)
    )[::-1][:20]

    records = []

    print(f"\nStrategy = {strategy}")

    for rank, index in enumerate(
        ranked_indices,
        start=1,
    ):
        record = {
            "rank": rank,
            "grid_index": int(index),
            "reference_potential_au": float(
                reference_potential[index]
            ),
            "candidate_potential_au": float(
                potential[index]
            ),
            "residual_au": float(
                residual[index]
            ),
            "absolute_residual_au": float(
                abs(residual[index])
            ),
            "nearest_real_atom_distance_bohr": (
                float(
                    nearest_real_distance[index]
                )
            ),
            "grid_xyz_bohr": [
                float(value)
                for value in grid_xyz_bohr[
                    index
                ]
            ],
        }

        records.append(record)

        print(
            f"rank={rank:>2} "
            f"grid_index={index:>5} "
            f"reference="
            f"{record['reference_potential_au']: .8e} "
            f"candidate="
            f"{record['candidate_potential_au']: .8e} "
            f"residual="
            f"{record['residual_au']: .8e} "
            f"rmin_real="
            f"{record['nearest_real_atom_distance_bohr']:.6f}"
        )

    largest_error_records[
        strategy
    ] = records


print("\n[10] WRITE POINTWISE SUMMARY")

pointwise_csv = (
    execution_dir
    / "QM_F06_UPPER_V7A_R1_CAP_REDISTRIBUTION_ELECTROSTATIC_COMPARISON.csv"
)

with pointwise_csv.open(
    "w",
    encoding="utf-8",
    newline="",
) as handle:
    fieldnames = [
        "grid_index",
        "x_bohr",
        "y_bohr",
        "z_bohr",
        "nearest_real_atom_distance_bohr",
        "reference_full_RESP_potential_au",
    ]

    for strategy in strategy_columns:
        fieldnames.extend(
            [
                f"{strategy}_potential_au",
                f"{strategy}_residual_au",
            ]
        )

    writer = csv.DictWriter(
        handle,
        fieldnames=fieldnames,
    )

    writer.writeheader()

    for index in range(
        len(grid_xyz_bohr)
    ):
        row = {
            "grid_index": index,
            "x_bohr": grid_xyz_bohr[
                index, 0
            ],
            "y_bohr": grid_xyz_bohr[
                index, 1
            ],
            "z_bohr": grid_xyz_bohr[
                index, 2
            ],
            "nearest_real_atom_distance_bohr": (
                nearest_real_distance[index]
            ),
            "reference_full_RESP_potential_au": (
                reference_potential[index]
            ),
        }

        for strategy, potential in (
            strategy_potentials.items()
        ):
            row[
                f"{strategy}_potential_au"
            ] = potential[index]

            row[
                f"{strategy}_residual_au"
            ] = (
                potential[index]
                - reference_potential[index]
            )

        writer.writerow(row)


print("\n[11] SCIENTIFIC GATES")

finite_reference_gate = bool(
    np.all(
        np.isfinite(
            reference_potential
        )
    )
)

finite_candidate_gate = all(
    bool(
        np.all(
            np.isfinite(potential)
        )
    )
    for potential in (
        strategy_potentials.values()
    )
)

neutrality_gate = all(
    abs(float(np.sum(charges)))
    <= 5.0e-6
    for charges in (
        strategy_charges.values()
    )
)

grid_count_gate = (
    len(grid_xyz_bohr) == 24835
)

gates = {
    "upstream_comparison_gate": True,
    "VPOT_hash_gate": True,
    "full_atom_count_gate": (
        len(full_rows) == 52
    ),
    "real_atom_count_gate": (
        len(real_rows) == 37
    ),
    "grid_count_gate": (
        grid_count_gate
    ),
    "finite_reference_gate": (
        finite_reference_gate
    ),
    "finite_candidate_gate": (
        finite_candidate_gate
    ),
    "neutrality_gate": neutrality_gate,
    "pointwise_csv_created_gate": (
        pointwise_csv.is_file()
        and pointwise_csv.stat().st_size > 0
    ),
    "no_strategy_adopted_gate": True,
}

for name, value in gates.items():
    print(
        f"{name} = "
        f"{'PASS' if value else 'FAIL'}"
    )

all_gates_pass = all(
    gates.values()
)


print("\n[12] WRITE JSON REPORT")

report_json = (
    execution_dir
    / "QM_F06_UPPER_V7A_R1_CAP_REDISTRIBUTION_ELECTROSTATIC_AUDIT.json"
)

decision = (
    "D039_A3_CAP_REDISTRIBUTION_ELECTROSTATIC_AUDIT_PASS_"
    "MULTICRITERIA_SELECTION_REVIEW_AUTHORIZED"
    if all_gates_pass
    else
    "D039_A3_CAP_REDISTRIBUTION_ELECTROSTATIC_AUDIT_"
    "REVIEW_REQUIRED"
)

report = {
    "generated_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "decision": decision,
    "source_execution_directory": str(
        execution_dir.resolve()
    ),
    "reference_definition": (
        "COULOMB_POTENTIAL_OF_ALL_52_RESP_STAGE1_CHARGES"
    ),
    "candidate_definition": (
        "COULOMB_POTENTIAL_OF_37_RETAINED_REAL_ATOMS"
    ),
    "source_identity": {
        "VPOT": str(
            VPOT.resolve()
        ),
        "VPOT_sha256": sha256(
            VPOT
        ),
        "transferability_csv": str(
            transferability_csv.resolve()
        ),
        "transferability_csv_sha256": sha256(
            transferability_csv
        ),
        "redistribution_comparison_csv": str(
            comparison_csv.resolve()
        ),
        "redistribution_comparison_csv_sha256": sha256(
            comparison_csv
        ),
        "redistribution_comparison_json": str(
            comparison_json.resolve()
        ),
        "redistribution_comparison_json_sha256": sha256(
            comparison_json
        ),
    },
    "reference_summary": {
        "point_count": int(
            len(reference_potential)
        ),
        "minimum_au": float(
            np.min(reference_potential)
        ),
        "maximum_au": float(
            np.max(reference_potential)
        ),
        "mean_au": float(
            np.mean(reference_potential)
        ),
        "std_au": float(
            np.std(reference_potential)
        ),
    },
    "strategy_metrics": (
        strategy_metrics
    ),
    "global_RMSE_ranking": (
        ranking
    ),
    "largest_error_records": (
        largest_error_records
    ),
    "gates": gates,
    "authorizations": {
        "multicriteria_strategy_selection_review_authorized": (
            all_gates_pass
        ),
        "redistribution_strategy_adoption_authorized": False,
        "RESP_stage2_execution_authorized": False,
        "charge_adoption_authorized": False,
        "force_field_adoption_authorized": False,
    },
    "outputs": {
        "pointwise_csv": str(
            pointwise_csv.resolve()
        ),
        "pointwise_csv_sha256": sha256(
            pointwise_csv
        ),
    },
}

report_json.write_text(
    json.dumps(
        report,
        indent=2,
    )
    + "\n",
    encoding="utf-8",
)

print(f"pointwise_csv = {pointwise_csv}")
print(
    f"pointwise_csv_sha256 = "
    f"{sha256(pointwise_csv)}"
)
print(f"report_json = {report_json}")
print(
    f"report_json_sha256 = "
    f"{sha256(report_json)}"
)


print("\n[13] DECISION")

print(f"decision = {decision}")
print(
    "multicriteria_strategy_selection_review_authorized = "
    f"{all_gates_pass}"
)
print("redistribution_strategy_adoption_authorized = False")
print("RESP_stage2_execution_authorized = False")
print("charge_adoption_authorized = False")
print("force_field_adoption_authorized = False")
print("=" * 100)
