#!/usr/bin/env python3

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]

MODEL = (
    ROOT
    / "runs"
    / "phase1B"
    / "day041_lammps_indexed_model"
    / "PHASE1B_LAMMPS_INDEXED_MODEL.json"
)

RUN = (
    ROOT
    / "runs"
    / "phase1B"
    / "day041_lammps_export"
)

RUN.mkdir(parents=True, exist_ok=True)

model = json.loads(MODEL.read_text())

counts = model["counts"]
tables = model["type_tables"]


outfile = RUN / "data.lammps"


atoms = model["system"]["atoms"]

xs = [float(a["x_A"]) for a in atoms]
ys = [float(a["y_A"]) for a in atoms]
zs = [float(a["z_A"]) for a in atoms]

MARGIN = 5.0

xlo = min(xs) - MARGIN
xhi = max(xs) + MARGIN

ylo = min(ys) - MARGIN
yhi = max(ys) + MARGIN

zlo = min(zs) - MARGIN
zhi = max(zs) + MARGIN



def writeln(f="", fp=None):
    fp.write(f"{f}\n")


def write_header(fp):

    writeln("Phase1B autogenerated topology", fp)
    writeln("", fp)

    writeln(f"{counts['atom_count']} atoms", fp)
    writeln(f"{counts['bond_count']} bonds", fp)
    writeln(f"{counts['angle_count']} angles", fp)
    writeln(f"{counts['improper_count']} impropers", fp)
    writeln(f"{counts['dihedral_count']} dihedrals", fp)
    writeln("", fp)

    writeln(f"{len(tables['atoms'])} atom types", fp)
    writeln(f"{len(tables['bonds'])} bond types", fp)
    writeln(f"{len(tables['angles'])} angle types", fp)
    writeln(f"{len(tables['impropers'])} improper types", fp)
    writeln(f"{len(tables['dihedrals'])} dihedral types", fp)
    writeln("", fp)

    writeln(f"{xlo:12.6f} {xhi:12.6f} xlo xhi", fp)
    writeln(f"{ylo:12.6f} {yhi:12.6f} ylo yhi", fp)
    writeln(f"{zlo:12.6f} {zhi:12.6f} zlo zhi", fp)

    writeln("", fp)


def write_masses(fp):

    masses = {

        "B":10.811,
        "N":14.007,
        "HB":1.0078,
        "HN":1.0078

    }

    reverse = {v:k for k,v in tables["atoms"].items()}

    writeln("Masses", fp)
    writeln("", fp)

    for idx in sorted(reverse):

        name = reverse[idx]

        writeln(
            f"{idx:3d} {masses[name]:12.6f} # {name}",
            fp
        )

    writeln("", fp)


def write_pair_coeffs(fp):

    coeff = {

        "B":(0.069240,3.308700),

        "N":(0.047299,3.217400),

        "HB":(0.070000,2.420000),

        "HN":(0.059000,2.420000)

    }

    reverse = {v:k for k,v in tables["atoms"].items()}

    writeln("Pair Coeffs", fp)
    writeln("", fp)

    for idx in sorted(reverse):

        t = reverse[idx]

        eps,sigma = coeff[t]

        writeln(
            f"{idx:3d} {eps:10.6f} {sigma:10.6f}",
            fp
        )

    writeln("", fp)


def write_bond_coeffs(fp):

    coeff = {}

    for bond in model["system"]["bonds"]:

        name = bond["parameter_type"]

        value = (
            float(bond["k_lammps_real_kcalmol_A2"]),
            float(bond["r0_A"]),
        )

        if name in coeff and coeff[name] != value:
            raise RuntimeError(
                f"Inconsistent bond parameters for {name}: "
                f"{coeff[name]} vs {value}"
            )

        coeff[name] = value

    reverse = {v:k for k,v in tables["bonds"].items()}

    if set(coeff) != set(reverse.values()):
        raise RuntimeError(
            "Bond coefficient/type-table mismatch: "
            f"coeff={sorted(coeff)} "
            f"table={sorted(reverse.values())}"
        )

    writeln("Bond Coeffs", fp)
    writeln("", fp)

    for idx in sorted(reverse):

        name = reverse[idx]
        k,r = coeff[name]

        writeln(
            f"{idx:3d} {k:12.6f} {r:10.6f} # {name}",
            fp
        )

    writeln("", fp)


def write_angle_coeffs(fp):

    coeff = {}

    for angle in model["system"]["angles"]:

        name = angle["parameter_type"]

        value = (
            float(angle["k_lammps_real_kcalmol_rad2"]),
            float(angle["theta0_deg"]),
        )

        if name in coeff and coeff[name] != value:
            raise RuntimeError(
                f"Inconsistent angle parameters for {name}: "
                f"{coeff[name]} vs {value}"
            )

        coeff[name] = value

    reverse = {v:k for k,v in tables["angles"].items()}

    if set(coeff) != set(reverse.values()):
        raise RuntimeError(
            "Angle coefficient/type-table mismatch: "
            f"coeff={sorted(coeff)} "
            f"table={sorted(reverse.values())}"
        )

    writeln("Angle Coeffs", fp)
    writeln("", fp)

    for idx in sorted(reverse):

        name = reverse[idx]
        k,theta = coeff[name]

        writeln(
            f"{idx:3d} {k:12.6f} {theta:10.6f} # {name}",
            fp
        )

    writeln("", fp)


def write_improper_coeffs(fp):

    coeff = {}

    for imp in model["system"]["impropers"]:

        name = imp["parameter_type"]

        value = (
            float(imp["k_lammps_real_kcalmol"]),
            float(imp["theta0_deg"]),
        )

        if name in coeff and coeff[name] != value:
            raise RuntimeError(
                f"Inconsistent improper parameters for {name}: "
                f"{coeff[name]} vs {value}"
            )

        coeff[name] = value

    reverse = {v:k for k,v in tables["impropers"].items()}

    if set(coeff) != set(reverse.values()):
        raise RuntimeError(
            "Improper coefficient/type-table mismatch: "
            f"coeff={sorted(coeff)} "
            f"table={sorted(reverse.values())}"
        )

    writeln("Improper Coeffs", fp)
    writeln("", fp)

    for idx in sorted(reverse):

        name = reverse[idx]
        k,theta = coeff[name]

        writeln(
            f"{idx:3d} {k:12.6f} {theta:10.6f} # {name}",
            fp
        )

    writeln("", fp)



def write_dihedral_coeffs(fp):

    writeln("Dihedral Coeffs", fp)
    writeln("", fp)

    for idx in (1,2,3):

        writeln(
            f"{idx:3d} 0.0 0.0 0.0 0.0",
            fp
        )

    writeln("", fp)



def write_atoms(fp):

    writeln("Atoms", fp)
    writeln("", fp)

    atom_type_ids = tables["atoms"]

    for atom in model["system"]["atoms"]:

        idx = atom["lammps_index"]

        typ = atom_type_ids[atom["forcefield_type"]]

        q = float(atom["RESP_charge_e"])

        x = float(atom["x_A"])
        y = float(atom["y_A"])
        z = float(atom["z_A"])

        writeln(
            f"{idx:4d} 1 {typ:2d} {q: .8f} {x: .8f} {y: .8f} {z: .8f}",
            fp
        )

    writeln("", fp)


def write_bonds(fp):

    writeln("Bonds", fp)
    writeln("", fp)

    type_ids=tables["bonds"]

    for i,b in enumerate(model["system"]["bonds"],1):

        t=type_ids[b["parameter_type"]]

        a1,a2=b["indices"]

        writeln(f"{i:4d} {t:2d} {a1:4d} {a2:4d}",fp)

    writeln("",fp)


def write_angles(fp):

    writeln("Angles",fp)
    writeln("",fp)

    type_ids=tables["angles"]

    for i,a in enumerate(model["system"]["angles"],1):

        t=type_ids[a["parameter_type"]]

        i1,i2,i3=a["indices"]

        writeln(f"{i:4d} {t:2d} {i1:4d} {i2:4d} {i3:4d}",fp)

    writeln("",fp)


def write_impropers(fp):

    writeln("Impropers",fp)
    writeln("",fp)

    type_ids=tables["impropers"]

    for i,obj in enumerate(model["system"]["impropers"],1):

        t=type_ids[obj["parameter_type"]]

        c,n1,n2,n3=obj["indices"]

        writeln(f"{i:4d} {t:2d} {c:4d} {n1:4d} {n2:4d} {n3:4d}",fp)

    writeln("",fp)


def write_dihedrals(fp):

    writeln("Dihedrals",fp)
    writeln("",fp)

    type_ids=tables["dihedrals"]

    for i,obj in enumerate(model["system"]["dihedrals"],1):

        t=type_ids[obj["parameter_type"]]

        a,b,c,d=obj["indices"]

        writeln(f"{i:4d} {t:2d} {a:4d} {b:4d} {c:4d} {d:4d}",fp)

    writeln("",fp)


with open(outfile,"w") as fp:

    write_header(fp)

    write_masses(fp)

    write_pair_coeffs(fp)

    write_bond_coeffs(fp)

    write_angle_coeffs(fp)

    write_improper_coeffs(fp)

    write_dihedral_coeffs(fp)

    write_atoms(fp)
    write_bonds(fp)
    write_angles(fp)
    write_impropers(fp)
    write_dihedrals(fp)

print("="*100)
print("DAY041 / PHASE1B-A23")
print("LAMMPS WRITER (FORCE FIELD)")
print("="*100)
print()
print(outfile)
print()
print("FORCE_FIELD_SECTIONS_WRITTEN")
